const actions = {
    instances: {
        PRELOAD_INSTANCES: 'PRELOAD_INSTANCES',
        INSTANCES_PRELOADED: 'INSTANCES_PRELOADED',
        LOAD_INSTANCES_FOR_NAMESPACE: 'LOAD_INSTANCES_FOR_NAMESPACE',
        INSTANCES_LOADED: 'INSTANCES_LOADED'
    },

    namespaces: {
        PRELOAD_NAMESPACES: 'PRELOAD_NAMESPACES',
        NAMESPACES_PRELOADED: 'NAMESPACES_PRELOADED'
    },

    session: {
        UPDATE_NAMESPACE: 'UPDATE_NAMESPACE'
    }
};

export default actions;
