const instanceActions = {
    PRELOAD_INSTANCES: 'PRELOAD_INSTANCES',
    INSTANCES_PRELOADED: 'INSTANCES_PRELOADED',
    LOAD_INSTANCES_FOR_NAMESPACE: 'LOAD_INSTANCES_FOR_NAMESPACE',
    INSTANCES_LOADED: 'INSTANCES_LOADED'
};

export default instanceActions;
